const draw1 = [
    [N, N, N, N, N, X, X, X, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, N, N, N, N, N],
    [N, N, N, X, X, N, N, N, N, N, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, X, N, X, X, N, N, N],
    [N, N, X, N, N, N, N, N, N, N, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, X, X, X, X, N, X, N, N],
    [N, X, N, N, X, X, N, N, N, X, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, N, N, X, X, X, N, N, X, X, N, X, N],
    [N, X, N, X, N, N, X, N, X, N, N, X, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, N, N, X, X, X, N, N, X, N, X, N],
    [X, N, N, X, N, X, X, N, X, N, X, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, N, N, X, X, X, N, N, X, X, X, X],
    [X, N, N, X, N, X, X, N, X, N, X, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, N, N, N, N, X, N, N, N, N, X, X, X, X],
    [X, N, N, X, N, N, X, N, X, N, N, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, N, N, N, X, X, N, N, N, X, X, X, X, X],
    [X, N, N, N, X, X, N, N, N, X, X, N, N, N, X, X, O, O, O, O, O, O, O, O, O, O, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X],
    [X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, O, X, O, O, X, X, X, O, O, O, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X],
    [X, N, N, N, N, N, N, N, N, N, N, X, N, N, N, O, O, X, X, O, O, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, N, X, X, X],
    [N, X, N, N, N, N, N, N, N, N, X, N, N, X, X, O, O, O, O, O, X, X, X, X, X, X, X, O, O, X, X, X, X, X, X, X, X, X, N, X, X, X, N],
    [N, X, N, N, N, N, N, N, X, X, N, N, N, X, O, X, X, O, O, O, X, X, X, X, X, O, O, O, O, X, X, X, X, X, X, X, N, N, X, X, X, X, N],
    [N, N, X, N, N, N, N, N, N, N, N, N, X, O, O, O, O, X, X, X, X, X, X, X, O, O, O, O, O, O, X, X, X, X, X, X, X, X, X, X, X, N, N],
    [N, N, N, X, X, N, N, N, N, N, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, X, X, X, X, N, N, N],
    [N, N, N, N, N, X, X, X, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, N, N, N, N, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N],
    [N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, N, N, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X]
]

const draw2 = [
    [N, N, N, N, N, X, X, X, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, N, N, N, N, N],
    [N, N, N, X, X, N, N, N, N, N, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, X, N, X, X, N, N, N],
    [N, N, X, N, N, N, N, N, N, N, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, X, X, X, X, N, X, N, N],
    [N, X, N, N, X, X, N, N, N, X, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, N, N, X, X, X, N, N, X, X, N, X, N],
    [N, X, N, X, N, N, X, N, X, N, N, X, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, N, N, X, X, X, N, N, X, N, X, N],
    [X, N, N, X, N, X, X, N, X, N, X, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, N, N, X, X, X, N, N, X, X, X, X],
    [X, N, N, X, N, X, X, N, X, N, X, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, N, N, N, N, X, N, N, N, N, X, X, X, X],
    [X, N, N, X, N, N, X, N, X, N, N, X, N, N, X, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, N, N, N, X, X, N, N, N, X, X, X, X, X],
    [X, N, N, N, X, X, N, N, N, X, X, N, N, N, X, X, O, O, O, X, X, X, O, O, O, O, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X],
    [X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, O, X, X, X, O, O, X, X, X, O, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X],
    [X, N, N, N, N, N, N, N, N, N, N, X, N, N, N, O, O, O, O, O, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, N, X, X, X],
    [N, X, N, N, N, N, N, N, N, N, X, N, N, X, X, O, O, O, O, O, X, X, X, X, X, X, X, O, O, X, X, X, X, X, X, X, X, X, N, X, X, X, N],
    [N, X, N, N, N, N, N, N, X, X, N, N, N, X, O, X, X, X, X, X, X, X, X, X, X, O, O, O, O, X, X, X, X, X, X, X, N, N, X, X, X, X, N],
    [N, N, X, N, N, N, N, N, N, N, N, N, X, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, X, X, X, X, X, X, X, X, X, X, X, N, N],
    [N, N, N, X, X, N, N, N, N, N, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, X, X, X, X, N, N, N],
    [N, N, N, N, N, X, X, X, X, X, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, X, X, X, X, X, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N, N],
    [N, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, N, N, N, N, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N],
    [N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, N, N, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X, N, X]
]
const PIXEL = { N: N, O: O, X: X };